name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["develop", "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Code analysis
        run: dotnet build --configuration Release --verbosity normal /p:TreatWarningsAsErrors=true
      - name: Test
        run: dotnet test --no-build --verbosity normal
        
  sonar_analysis:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        # --- CETTE LIGNE EST LA CLÉ ---
        continue-on-error: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    # On dépend de build et sonar_analysis
    needs: [build, sonar_analysis]
    # On s'assure que build a réussi, mais on ignore l'état de sonar_analysis
    if: |
      always() && 
      needs.build.result == 'success' && 
      github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker build --target api-final -t elix-api:latest -f Dockerfile.prod .
          docker build --target webapp-final -t elix-webapp:latest -f Dockerfile.prod .

      - name: Save Images
        run: |
          docker save elix-api:latest elix-webapp:latest | gzip > elix-apps.tar.gz

      - name: Copy to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "elix-apps.tar.gz,compose.yml"
          target: ${{ secrets.VPS_TARGET_PATH }}

      - name: Remote Update via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/elix-app
            if [ -f elix-apps.tar.gz ]; then
              gunzip -c elix-apps.tar.gz | docker load
              docker compose up -d
              rm elix-apps.tar.gz
              docker image prune -f
            else
              echo "Fichier elix-apps.tar.gz non trouvé !"
              exit 1
            fi